# Python Poetry CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:

      - setup_remote_docker:
          docker_layer_caching: true

      #- run:
      #    name: Update apt
      #    command: sudo apt-get update

      #- run:
      #  name: Install Docker client
      #  command: sudo apt-get install -y docker.io docker-compose

      - checkout

      - run:
          name: update poetry to 1.0.5
          command: |
            sudo pip install 'poetry==1.0.5'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            poetry install

      - save_cache:
          key: v1-dependencies-{{ checksum "poetry.lock" }}
          paths:
            - ./venv

      # run tests!
      - run:
          name: run tests
          command: poetry run pytest
          environment:
            REMOTE_DOCKER_SSH_HOST: remote-docker

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1
